### ISSUE TITLE
Update Clinicians page with information about younger patients

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#117]
Currently the Information For Clinicians page (https://genderkit.org.uk/resources/clinicians/) gives details about the policies for adults, but not for younger people.

**Comment by jlphackett** [comment]
I added a link to the NHS England service spec for GIDS. There's probably equivalent documents for the other nations?

**Comment by jlphackett** [comment]
Okay, so it turns out there isn't much in the way of specific youth policy, but here's what I've managed to find:

For Scotland, there seems to be no specific protocol for young people; appendix 5 of the main protocol says under 16s should contact either a GP or GIC and will then be referred on to Tavistock & Portman, who will presumably follow the England guidance.
![Screenshot 2020-09-18 at 22 22 42](https://user-images.githubusercontent.com/39128460/93646139-89133180-f9fd-11ea-89d3-9792df8bbfb7.png)

For Wales, there is no specific policy for children, but the adult policy specifies that referrals can only be made for people at least 17.5 years old and that they will not receive any appointments until they reach 18. Tavistock & Portman handle care for under 18s, again presumably following the England guidance. You don't then need to be reassessed when care is transferred.

For NI, there is no specific protocols that I can find at all. However it might be worth noting somewhere on the site that KOI (the NI youth service) expect referrals via CAMHS, rather than direct from the GP. (Also apparently when they transfer care the adult clinic will re-assess, even though it's basically the same organisation??) [This FAQ](https://belfasttrust.hscni.net/wp-admin/admin-ajax.php?juwpfisadmin=false&action=wpfd&task=file.download&wpfd_category_id=195&wpfd_file_id=2704&token=b71abf27d71276ea3ddc7e24739ea87a&preview=1), though aimed at patients rather than clinicians, may be useful.
