### ISSUE TITLE
Split the "Screening Tests" section from "Updating NHS patient details"

### ISSUE THREAD

**Issue by Kikami** [genderkit/genderkit#75]
I'd argue that the screening tests (a particularly medical issue) are very much relevant to the status of your NHS patient details - which are more of an administrative issue - but perhaps best separated into its own page and linked from the patient details page.

**Comment by fallax** [comment]
We've got a bit of a problem site-wide at the moment that some of the pages are just Too Big and have too much on them.

#67 is a good example of this. With that issue, it's a bit more obvious within the site structure where the new pages should sit. With this, there isn't really an obvious place.

I think the real problem is that we're trying to maintain some information that we shouldn't, and we should really be referring to an NHS page or booklet somewhere. Luckily since I wrote the original page, the NHS have produced exactly that booklet:

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/623309/Transgender_cross_programme_screening_leaflet.pdf

**Comment by fallax** [comment]
Updated page to just refer to NHS guidance rather than reproducing that work on this website.
