### ISSUE TITLE
it'd be cool if the build process could flag internal (and possibly external) 404s

### ISSUE THREAD

**Issue by tinruufu** [genderkit/genderkit#97]
this could prevent issues like #96

**Comment by fallax** [comment]
There's currently a manual step that can be run using /scripts/broken-link-checker.sh

This finds *most*, but not all, broken links. (Unfortunately it turns out that it is surprisingly difficult to detect broken links with 100% accuracy.)

Running this as part of the CI build should definitely be considered for the next major version.

**Comment by fallax** [comment]
Fixed by https://github.com/genderkit/genderkit/commit/f7fb6156577eff07ffcfe763590f19bb00894368 - now checks internal and external links using Github Actions on each commit
